# Dependencies
gems:
  - jekyll-sitemap
  - jekyll-redirect-from

markdown:         redcarpet
redcarpet:
    extensions:   ["autolink", "tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            QA-Tools
tagline:          'Quality assurance utilities for functional tests'
slogan:           'PHP PageObjects made easy.'
description:      'Easy-to-use way of interaction with web-page elements in functional tests using PageObject pattern.'
url:              http://www.qa-tools.io

exclude:          [vendor, atlassian-ide-plugin.xml, phpunit.xml, composer.lock, node_modules]
timezone:         Europe/Riga

author:
  name:           'Alexander Obuhovich'
  url:            https://twitter.com/aik099

# Custom vars
github:
  repo:           https://github.com/qa-tools/qa-tools

api:
  url:            http://api.qa-tools.io/master/index.html
